### ISSUE TITLE
Android: No way to send Super key

### ISSUE THREAD

**Issue by thomasqueirozb** [bk138/multivnc#41]
Installed from Play Store

**Is your feature request related to a problem? Please describe.**
Cannot send the Super (Windows) key and combinations. Since I am using a window manager, combination using the super key are essential to me and I can't find a way to send this keystroke.

**Describe the solution you'd like**
A way to send key combinations with the super key included

**Comment by bk138** [comment]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle :-)

**Comment by bk138** [comment]
@BrunoSDomingues Politely asking what's wrong asking for some kind of compensation for time spent and work done? It's not a hard requirement, simply a possibility to say thanks.

**Comment by BrunoSDomingues** [comment]
@bk138 I personally don't see the issue as a feature request, but rather a bug. I don't have any issue with asking for compensation for work done, especially when someone asks for a new feature, but in my opinion the issue is not a new feature. If you got a keyboard for example, but a key isn't working, it isn't correct that whoever made the keyboard asks you extra to fix it.

**Comment by bk138** [comment]
@BrunoSDomingues Let's agree we disagree :-). My point is twofold: a) the line between a missing feature and a bug is sometimes quite thin. b) If you get a keyboard for free from someone as a present and it does not have a special key you might want, I maintain it's OK that the person who made you that present asks a little compensation for the extra work she/he has fulfilling your special wish. But let's not start a flame war, I just wanted to raise some empathy  for a developer's POV. :-)
